/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '1054737' at '6/28/16 2:42 PM' with Gradle 2.0
 *
 * @author 1054737, @date 6/28/16 2:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
